### ISSUE TITLE
protofu doesn't pick up protofu.yaml configuration

### ISSUE THREAD

**Issue by bivens-dev** [jtmcdole/protofu#5]
## Expected Behavior
I have a repo set up with the following directory structure
```
/api
 - protos
   - v1 
 - (dart package with protofu.yaml at root)
/app
- (flutter app)
/server
- (dart app)
```

When I start from the root directory and run
```bash
cd api
protofu
```

I would expect that it would pick up the protofu.yaml that is also in the same directory but it doesn't appear to for some reason.

## Actual Behavior
I tried toggling grpc support on and off and changing the output directory and protoc versions. None of the changes were picked up and everything appeared to just be running with the default configuration settings and ignoring the file. 

Unsure if it is in anyway related but I do also have a local copy of protoc already installed on the machine at `/home/$USER/.local/bin/protoc` which is on my path. Could that somehow be causing an issue or should I be looking elsewhere do you think?

Also included my `./api/protofu.yaml` config in case anything looks weird.

```yaml
compiler:
  # optional: pass grpc flag to --dart_out protoc string. Defaults to "false"
  grpcEnabled: true

options:
  # optional: pass the --experimental_allow_proto3_optional flag
  experimentalAllowProto3Optional: True

sources:
  - "proto/"
output: "lib/src/compiled"

include:
  - git:
      url: https://github.com/googleapis/googleapis.git
      ref: master # branch

```
